export const textureRequires = {
    LunchFaceHole: require('./images/lunch face hole.png'),
    Apple: require('./images/apple.png'),
    Dummy: require('./images/dummy.png'),
    PurpleGuy: require('./images/purple guy.png'),
    CardboardBox: require('./images/cardboard box.png'),
    Heart: require('./images/heart.png'),
    Flower: require('./images/flower.png'),
    Monkey: require('./images/monkey.png'),
    Elephant: require('./images/elephant.png'),
    Cloud: require('./images/cloud.png'),
    FaceHole: require('./images/face hole.png'),
    Shadow: require('./images/shadow.png'),
    SleepingKoala: require('./images/sleeping koala.png'),
    Zed: require('./images/zed.png'),
    Anemone: require('./images/anemone.png'),
    BlueFish: require('./images/bluefish.png'),
    ClownFish: require('./images/clownfish.png'),
    StarFish: require('./images/starfish.png'),
    Panda: require('./images/panda.png'),
};
